### ISSUE TITLE
sqlalchemy.exc.InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.

### ISSUE THREAD

**Issue by ESWZY** [ESWZY/telegram-news#8]
When there are high concurrent requests to datadase with read and write statements, the following exception usually raises.

```
Traceback (most recent call last):
  File "\telegram-news\telegram_news\template\common.py", line 685, in _post
    self._insert_one_item(news_id)
  File "\telegram-news\telegram_news\template\common.py", line 589, in _insert_one_item
    self._db.execute(query, {"news_id": news_id})
  File "C:\Python\lib\site-packages\sqlalchemy\orm\session.py", line 1277, in execute
    return self._connection_for_bind(bind, close_with_result=True).execute(
  File "C:\Python\lib\site-packages\sqlalchemy\orm\session.py", line 1138, in _connection_for_bind
    return self.transaction._connection_for_bind(
  File "C:\Python\lib\site-packages\sqlalchemy\orm\session.py", line 408, in _connection_for_bind
    self._assert_active()
  File "C:\Python\lib\site-packages\sqlalchemy\orm\session.py", line 281, in _assert_active
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: This session is in 'prepared' state; no further SQL can be emitted within this transaction.
```

That may because we (have to) share one database session for many threads. What should I do to avoid it. 

Maybe it is not a fatal error, because nothing happened after that exception. Anyway, it's not a good news.

**Comment by ESWZY** [comment]
In tests, this exception can be seen only when the exception raiser thread is reading database and other thread is writing database. 

And if this exception happened, exception raiser thread will stop this loop and restart. It will not effect other threads.

So, for now, it's not harm for the correctness. It will just delay the reading by one loop time.

**Comment by aminPial** [comment]
@ESWZY so you are telling that we shouldn't be concerned about this? we are facing this in our production environment for a while. Can't figure out how to solve it or should we even be bothered about it! we are using FastApi (async of course) which is derived from the async Starlette framework.

**Comment by ESWZY** [comment]
> @ESWZY so you are telling that we shouldn't be concerned about this? we are facing this in our production environment for a while. Can't figure out how to solve it or should we even be bothered about it! we are using FastApi (async of course) which is derived from the async Starlette framework.

Hello! You can regard this as the database refused your transaction, and nothing has been done.

**Comment by aminPial** [comment]
Ok great so suppose i want to commit an update or a fresh row insertion. Then if this error happens mean that, no commit has taken place? do i need to do flush or something after this happens? what can be the workaround for this thing, mate?

**Comment by ESWZY** [comment]
> Ok great so suppose i want to commit an update or a fresh row insertion. Then if this error happens mean that, no commit has taken place? do i need to do flush or something after this happens? what can be the workaround for this thing, mate?

I think you should check the changing of db (If it is needed and you want), and try it again. It all depends on what your system does.
